CREATE TABLE IF NOT EXISTS employee(
	USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	MOBILE_NUMBER VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(255),
	DEPARTMENT VARCHAR(255)
);